name: "F1 Dashboard"
version: "0.5.0" # Increment version
slug: "f1_dashboard"
description: "F1 Telemetry Dashboard"
arch:
  - amd64 # Ensure no strange leading spaces
  - aarch64
  - armv7
init: false
startup: application
boot: auto

ingress: false   # <<<< SET TO FALSE to disable standard Supervisor Ingress

# Keep direct port mapping for lovelylain/hass_ingress to connect to
ports:
  "8050/tcp": 8050 # Host port 8050 maps to container port 8050
ports_description:
  "8050/tcp": "F1 Dashboard Direct Access Port"